language: c
script: asdf plugin-test flink https://github.com/austince/asdf-flink.git
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
  - ./bin/import-release-team-keyring
osx_image: xcode8.2
os:
  - linux
